import { GoogleSpreadsheet } from "google-spreadsheet";

exports.main = async (event) => {
  // Initialize the sheet - doc ID is the long id in the sheets URL
  const doc = new GoogleSpreadsheet(process.env.DOC_ID)
  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  const body = JSON.parse(event.body);
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.CLIENT_EMAIL,
    private_key: process.env.PRIVATE_KEY
});
  await doc.loadInfo(); // loads document properties and worksheets
  const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
  await sheet.loadCells(body.range);

  await body.cells.forEach(async (cell, index) => {
    var data = await sheet.getCellByA1(cell);
    console.log(data);
    data.value = body.data[index];
  });

  await sheet.saveUpdatedCells();

  return {
    statusCode: 200,
    headers: { "Content-Type": "text/plain" },
    body: "Added cells",
  };
};
