import { GoogleSpreadsheet } from "google-spreadsheet";
exports.main = async (event) => {
  const doc = new GoogleSpreadsheet(process.env.DOC_ID);
  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  const body = JSON.parse(event.body);

  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.CLIENT_EMAIL,
    private_key: process.env.PRIVATE_KEY
});
  await doc.loadInfo();
  const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
  await sheet.setHeaderRow(["email", "timestamp"]);

  // append rowsnewDate.toUTCString()
  var date = new Date();
  var utc = date.getTime() + (date.getTimezoneOffset() * 60000);
  var newDate = new Date(utc + (3600000 * +8));
  await sheet.addRow({
    email: body.email,
    timestamp: newDate.toLocaleString(),
  });

  return {
    statusCode: 200,
    headers: { "Content-Type": "text/plain" },
    body: `Added row`,
  };
};
