import { GoogleSpreadsheet } from "google-spreadsheet";

exports.main = async (event) => {
  
  const doc = new GoogleSpreadsheet(process.env.DOC_ID)
  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  const limit = JSON.parse(event.queryStringParameters.limit);
  const offset = JSON.parse(event.queryStringParameters.offset);

  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.CLIENT_EMAIL,
    private_key: process.env.PRIVATE_KEY
});
  await doc.loadInfo();
  const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
  var data = [];
  // read rows
  const rows = await sheet.getRows({ limit: limit, offset: offset }); // can pass in { limit, offset }
  rows.forEach(async (row) => {
    data.push({ email: row.email, timestamp: row.timestamp });
  });
  console.log(data);
  return {
    statusCode: 200,
    headers: { "Content-Type": "text/plain" },
    body: JSON.stringify(data),
  };
};
